# Generated by Django 4.1 on 2025-12-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
