# Generated by Django 4.1 on 2026-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='email_confirm_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
