# Generated by Django 4.1 on 2026-01-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0004_extendeduser_email_confirm_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='phone_confirm',
            new_name='ozon_phone_confirm',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='ozon_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='phone_confirm_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='sdek_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='sdek_phone_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
