# Generated by Django 4.1 on 2026-01-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0005_rename_phone_confirm_extendeduser_ozon_phone_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
