# Generated by Django 4.1 on 2026-01-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0006_extendeduser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
