# Generated by Django 4.1 on 2026-01-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0007_extendeduser_first_name_extendeduser_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='password',
        ),
    ]
