# Generated by Django 4.2.21 on 2026-01-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0008_remove_extendeduser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='phone',
        ),
    ]
