# Generated by Django 4.1 on 2026-04-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0009_remove_extendeduser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
