# Generated by Django 4.2.21 on 2025-10-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozon_attribute_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_attribute_value', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_attribute_info', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_attribute_picture', models.FileField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozon_attribute_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_attribute_value', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_attribute_info', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_attribute_picture', models.FileField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='AutoModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozon_attribute_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_attribute_value', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_attribute_info', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_attribute_picture', models.FileField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
    ]
