# Generated by Django 4.1 on 2025-10-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobrand',
            name='ozon_attribute_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automodel',
            name='ozon_attribute_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automodel',
            name='ozon_attribute_value',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
