# Generated by Django 4.2.21 on 2025-10-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0002_alter_autobrand_ozon_attribute_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automodification',
            old_name='ozon_attribute_info',
            new_name='ozon_attribute_info_mod',
        ),
    ]
