# Generated by Django 4.2.21 on 2025-10-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0003_rename_ozon_attribute_info_automodification_ozon_attribute_info_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automodification',
            name='ozon_attribute_info_mod',
        ),
        migrations.AddField(
            model_name='automodification',
            name='ozon_attribute_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
