# Generated by Django 4.1 on 2025-10-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0004_remove_automodification_ozon_attribute_info_mod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDEK_Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
