# Generated by Django 4.1 on 2025-10-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0005_sdek_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdek_office',
            name='address_full',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sdek_office',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sdek_office',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sdek_office',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sdek_office',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
