# Generated by Django 4.1 on 2025-10-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0006_sdek_office_address_full_sdek_office_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdek_office',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sdek_office',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sdek_office',
            name='address_full',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
