# Generated by Django 4.1 on 2025-10-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0007_sdek_office_code_sdek_office_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdek_office',
            name='country',
        ),
        migrations.AddField(
            model_name='sdek_office',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
