# Generated by Django 4.1 on 2025-10-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0009_alter_sdek_office_address_alter_sdek_office_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDEK_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fias', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
