# Generated by Django 4.1 on 2025-10-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0010_sdek_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdek_city',
            name='city_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
