# Generated by Django 4.1 on 2025-10-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0011_sdek_city_city_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdek_city',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='sdek_city',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
