# Generated by Django 4.1 on 2025-10-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0012_sdek_city_latitude_sdek_city_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdek_office',
            name='type',
            field=models.CharField(default='PVZ', max_length=25),
        ),
    ]
