# Generated by Django 4.1 on 2025-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0013_sdek_office_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdek_office',
            name='city_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
