# Generated by Django 4.1 on 2026-01-02 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_delivery', '0001_initial'),
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('shipped', models.BooleanField(default=False)),
                ('delivery_point', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_cost', models.IntegerField(blank=True, null=True)),
                ('receiver_firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('corresponding_rhos_created', models.BooleanField(default=False)),
                ('bill', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delivery_order_uuid', models.UUIDField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_purchase.customer')),
                ('delivery_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_delivery.deliveryoperator')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
                ('article', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_purchase.order')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('article', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_purchase.cart')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
    ]
