# Generated by Django 4.2.21 on 2026-01-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
