# Generated by Django 4.1 on 2026-01-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0002_order_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_order_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
