# Generated by Django 4.2.21 on 2026-01-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0003_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
