# Generated by Django 4.1 on 2025-09-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='article',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_purchase.identifier'),
        ),
    ]
