# Generated by Django 4.1 on 2025-09-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0004_cartitem_article_order_identifier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderItem',
        ),
    ]
