# Generated by Django 4.1 on 2026-01-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0004_alter_cart_options_alter_cart_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_purchase.cart'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
