# Generated by Django 4.1 on 2026-01-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0005_alter_cartitem_cart_alter_cart_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
