# Generated by Django 4.1 on 2025-09-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0005_rename_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='article',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
