# Generated by Django 4.1 on 2025-09-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0006_orderitem_article_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
