# Generated by Django 4.1 on 2026-02-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0008_remove_order_cart_orderitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
