# Generated by Django 4.1 on 2025-09-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0008_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='identifier',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_purchase.order'),
        ),
    ]
