# Generated by Django 4.1 on 2025-10-11 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0007_product_update_true'),
        ('app_purchase', '0010_alter_order_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sum',
            new_name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
