# Generated by Django 4.1 on 2025-10-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0009_product_percent_product_total'),
        ('app_purchase', '0014_orderitem_sub_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.product')),
            ],
        ),
    ]
