# Generated by Django 4.1 on 2025-12-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0018_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='receiver_name',
            new_name='receiver_firstName',
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
