# Generated by Django 4.1 on 2025-12-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0001_initial'),
        ('app_purchase', '0019_rename_client_order_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_delivery.deliveryoperator'),
        ),
    ]
