# Generated by Django 4.1 on 2025-12-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0020_order_delivery_cost_order_delivery_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
