# Generated by Django 4.2.21 on 2025-12-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0022_remove_order_paid_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='corresponding_rhos_created',
            field=models.BooleanField(default=False),
        ),
    ]
