# Generated by Django 4.1 on 2025-12-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0023_order_corresponding_rhos_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
