# Generated by Django 4.1 on 2025-12-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0024_order_full_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
