# Generated by Django 4.1 on 2025-12-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purchase', '0026_alter_orderitem_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
