# Generated by Django 4.2.21 on 2025-05-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
