# Generated by Django 4.2.21 on 2025-05-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='response',
            new_name='ServerResponse',
        ),
    ]
