# Generated by Django 4.1 on 2026-02-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0002_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
