# Generated by Django 4.1 on 2026-02-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0003_review_rating_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='percent',
            field=models.CharField(default='0%', max_length=50),
        ),
    ]
