# Generated by Django 4.1 on 2026-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0005_alter_review_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='percent',
        ),
        migrations.AddField(
            model_name='review',
            name='ozon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
