# Generated by Django 4.1 on 2026-02-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0006_remove_review_percent_review_ozon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='percent',
            field=models.CharField(default='0%', max_length=50),
        ),
    ]
