# Generated by Django 5.1.6 on 2025-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('emumerator', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=160)),
                ('bar_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('article', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_id', models.CharField(max_length=50, null=True, unique=True)),
                ('EAN', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
