# Generated by Django 4.1 on 2025-12-31 08:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sum', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'documentType',
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(max_length=250)),
                ('ozon_id', models.CharField(blank=True, max_length=50, null=True)),
                ('article', models.CharField(blank=True, max_length=50, null=True)),
                ('bar_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_remainder', models.IntegerField(default=0)),
                ('incoming_quantity', models.IntegerField(null=True)),
                ('outgoing_quantity', models.IntegerField(null=True)),
                ('current_remainder', models.IntegerField(default=0)),
                ('av_price', models.IntegerField(default=0)),
                ('identifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.identifier')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='RemainderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ozon_sku', models.CharField(blank=True, max_length=50, null=True)),
                ('ozon_id', models.CharField(blank=True, max_length=50, null=True)),
                ('wb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('wb_bar_code', models.CharField(blank=True, max_length=50, null=True)),
                ('article', models.CharField(blank=True, max_length=50, null=True)),
                ('bar_code', models.CharField(blank=True, max_length=50, null=True)),
                ('total_retail_sum', models.IntegerField(default=0)),
                ('wholesale_price', models.IntegerField(default=0, null=True)),
                ('av_price', models.IntegerField(default=0, null=True)),
                ('retail_price', models.IntegerField(default=0)),
                ('pre_remainder', models.IntegerField(default=0)),
                ('incoming_quantity', models.IntegerField(null=True)),
                ('outgoing_quantity', models.IntegerField(null=True)),
                ('current_remainder', models.BigIntegerField(default=0)),
                ('update_check', models.BooleanField(default=False)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.document')),
                ('rho_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.documenttype')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('emumerator', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('auto_model', models.CharField(blank=True, max_length=160, null=True)),
                ('brand', models.CharField(blank=True, max_length=160, null=True)),
                ('brand_rus', models.CharField(blank=True, max_length=160, null=True)),
                ('model_short', models.CharField(blank=True, max_length=160, null=True)),
                ('model_short_rus', models.CharField(blank=True, max_length=160, null=True)),
                ('bar_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('article', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ozon_sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('wb_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('wb_bar_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('wb_true', models.BooleanField(default=True)),
                ('ozon_true', models.BooleanField(default=True)),
                ('site_true', models.BooleanField(default=True)),
                ('update_true', models.BooleanField(default=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('av_price', models.IntegerField(default=0)),
                ('total_sum', models.IntegerField(default=0)),
                ('ozon_retail_price', models.IntegerField(default=0)),
                ('wb_retail_price', models.IntegerField(default=0)),
                ('site_retail_price', models.IntegerField(default=0)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('percent', models.CharField(default='0%', max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('av_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('transactions', models.IntegerField(default=0)),
                ('image_1', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('image_4', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('image_5', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('image_6', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('image_7', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('video_1', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.documenttype'),
        ),
    ]
