# Generated by Django 5.1.6 on 2025-03-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_model',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
