# Generated by Django 4.1 on 2025-09-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ozon_retail_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='site_retail_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='wb_retail_price',
            field=models.IntegerField(default=0),
        ),
    ]
