# Generated by Django 5.1.6 on 2025-03-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_product_auto_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='EAN',
            new_name='ean',
        ),
    ]
