# Generated by Django 5.1.6 on 2025-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_rename_ean_product_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='emumerator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ozon_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
