# Generated by Django 4.2.21 on 2025-09-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_product_ozon_retail_price_product_site_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.document'),
        ),
    ]
