# Generated by Django 4.2.21 on 2025-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_alter_remainderhistory_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_short',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
