# Generated by Django 5.1.6 on 2025-03-02 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_alter_product_emumerator_alter_product_ozon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'documentType',
            },
        ),
        migrations.CreateModel(
            name='RemainderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=250)),
                ('imei', models.CharField(max_length=250)),
                ('sub_total', models.IntegerField(default=0)),
                ('wholesale_price', models.IntegerField(default=0, null=True)),
                ('av_price', models.IntegerField(default=0, null=True)),
                ('retail_price', models.IntegerField(default=0)),
                ('pre_remainder', models.IntegerField(default=0)),
                ('incoming_quantity', models.IntegerField(null=True)),
                ('outgoing_quantity', models.IntegerField(null=True)),
                ('current_remainder', models.BigIntegerField(default=0)),
                ('update_check', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.product')),
                ('rho_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.documenttype')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
