# Generated by Django 4.1 on 2026-04-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_product_search_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
