# Generated by Django 4.1 on 2026-04-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_report_brand_report_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='brand',
            new_name='manufacturer',
        ),
    ]
