# Generated by Django 4.2.21 on 2025-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_product_brand_product_model_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_rus',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_short_rus',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
