# Generated by Django 5.1.6 on 2025-03-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_documenttype_remainderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainderhistory',
            name='imei',
        ),
        migrations.AddField(
            model_name='remainderhistory',
            name='article',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='remainderhistory',
            name='bar_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
