# Generated by Django 4.1 on 2026-04-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_rename_brand_report_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_update_true',
            field=models.BooleanField(default=True),
        ),
    ]
