# Generated by Django 4.2.21 on 2025-09-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_product_brand_rus_product_model_short_rus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_true',
            field=models.BooleanField(default=True),
        ),
    ]
