# Generated by Django 5.1.6 on 2025-03-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_remove_remainderhistory_imei_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainderhistory',
            old_name='product_id',
            new_name='ozon_id',
        ),
    ]
