# Generated by Django 5.1.6 on 2025-03-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0007_rename_product_id_remainderhistory_ozon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='av_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
