# Generated by Django 4.1 on 2025-10-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0007_product_update_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='av_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
    ]
