# Generated by Django 4.1 on 2026-04-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0007_product_quantity_update_true'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document'},
        ),
        migrations.AddField(
            model_name='document',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
