# Generated by Django 4.1 on 2025-10-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0008_product_av_rating_product_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percent',
            field=models.CharField(default='0%', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
