# Generated by Django 5.1.6 on 2025-03-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0008_product_av_price_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
