# Generated by Django 4.1 on 2026-10-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0009_document_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wb_chartId',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
