# Generated by Django 4.2.21 on 2025-11-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0009_product_percent_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site_true',
            field=models.BooleanField(default=True),
        ),
    ]
