# Generated by Django 5.1.6 on 2025-03-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0009_product_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_price',
            new_name='total_sum',
        ),
    ]
