# Generated by Django 4.2.21 on 2025-12-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0010_product_site_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='previously_created',
            field=models.BooleanField(default=False),
        ),
    ]
