# Generated by Django 5.1.6 on 2025-03-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0010_rename_total_price_product_total_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainderhistory',
            old_name='sub_total',
            new_name='total_retail_sum',
        ),
    ]
