# Generated by Django 4.1 on 2026-10-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0010_product_wb_chartid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wb_chartId',
            new_name='wb_chrtId',
        ),
    ]
