# Generated by Django 4.2.21 on 2025-12-16 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0011_remainderhistory_previously_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainderhistory',
            old_name='previously_created',
            new_name='corresponding_rho_created',
        ),
    ]
