# Generated by Django 5.1.6 on 2025-03-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0011_rename_sub_total_remainderhistory_total_retail_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
