# Generated by Django 5.1.6 on 2025-03-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0012_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='ozon_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
