# Generated by Django 4.2.21 on 2025-12-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0012_rename_previously_created_remainderhistory_corresponding_rho_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainderhistory',
            name='corresponding_rho_created',
        ),
    ]
