# Generated by Django 5.1.6 on 2025-03-18 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0013_alter_remainderhistory_ozon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(max_length=250)),
                ('ozon_id', models.CharField(blank=True, max_length=50, null=True)),
                ('article', models.CharField(blank=True, max_length=50, null=True)),
                ('bar_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_remainder', models.IntegerField(default=0)),
                ('incoming_quantity', models.IntegerField(null=True)),
                ('outgoing_quantity', models.IntegerField(null=True)),
                ('current_remainder', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
