# Generated by Django 5.1.6 on 2025-03-20 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0016_report_idenifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='idenifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.identifier'),
        ),
    ]
