# Generated by Django 5.1.6 on 2025-03-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0017_alter_report_idenifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='idenifier',
            new_name='identifier',
        ),
    ]
