# Generated by Django 4.1 on 2025-05-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0019_report_av_price_alter_report_current_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
