# Generated by Django 4.1 on 2025-05-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0020_remainderhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
