# Generated by Django 4.1 on 2025-05-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0022_remainderhistory_ozon_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ozon_sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
