# Generated by Django 4.1 on 2025-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0023_report_ozon_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ozon_sku',
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
