# Generated by Django 4.1 on 2025-06-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0026_product_length_product_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_6',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_7',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
