# Generated by Django 4.1 on 2025-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0027_product_image_1_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wb_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
