# Generated by Django 4.1 on 2025-06-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0029_product_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wb_bar_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
