# Generated by Django 4.1 on 2025-08-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0031_document_remainderhistory_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='wb_bar_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='remainderhistory',
            name='wb_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
