# Generated by Django 4.2.21 on 2025-08-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0031_document_remainderhistory_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ozon_true',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wb_true',
            field=models.BooleanField(default=True),
        ),
    ]
