# Generated by Django 4.2.21 on 2025-08-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0032_product_ozon_true_product_wb_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='wb_bar_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='remainderhistory',
            name='wb_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
