# Generated by Django 4.2.21 on 2025-08-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0032_remainderhistory_wb_bar_code_remainderhistory_wb_id'),
        ('app_product', '0033_remainderhistory_wb_bar_code_remainderhistory_wb_id'),
    ]

    operations = [
    ]
